### ISSUE TITLE
Error while compiling the pipeline in 'kfp_pipeline_vertex_prebuilt.ipynb'

### ISSUE THREAD

**Issue by srikrishna-Challa** [GoogleCloudPlatform/asl-ml-immersion#405]
While compiling the pipeline and executing the command - !dsl-compile-v2 --py pipeline_vertex/pipeline_prebuilt.py --output $PIPELINE_JSON' in the notebook --> 'kfp_pipeline_vertex_prebuilt.ipynb', it fails with the following error:

Traceback (most recent call last):
  File "/home/jupyter/.local/bin/dsl-compile-v2", line 8, in <module>
    sys.exit(main())
  File "/home/jupyter/.local/lib/python3.10/site-packages/kfp/v2/compiler/main.py", line 174, in main
    compile_pyfile(
  File "/home/jupyter/.local/lib/python3.10/site-packages/kfp/v2/compiler/main.py", line 157, in compile_pyfile
    __import__(os.path.splitext(filename)[0])
  File "/home/jupyter/asl-ml-immersion/notebooks/kubeflow_pipelines/pipelines/solutions/pipeline_vertex/pipeline_prebuilt.py", line 23, in <module>
    **_from google_cloud_pipeline_components.experimental import (
ModuleNotFoundError: No module named 'google_cloud_pipeline_components.experimental'_**

I tried multiple fixes but it does not seem to work. Is it a mismatch in the packages within the image?

**Comment by tslapczynski** [comment]
upgrade the google-cloud-pipeline-components package by running :
**pip install google-cloud-pipeline-components --upgrade,**
& go to an older version of KFP, such as kfp==2.0.0b5, maybe it helps.
 versions of KFP may be the problem

**Comment by tslapczynski** [comment]
And so have U solved this problem ? :)

**Comment by takumiohym** [comment]
Any update on this?

**Comment by Sidhack47** [comment]
How to

**Comment by takumiohym** [comment]
Closing this issue since there is no response. Feel free to open if you have any further questions.
